### ISSUE TITLE
Processing Floats fails for all but the 0.0 short circuit

### ISSUE THREAD

**Issue by grempe** [cryptosphere/objecthash-ruby#5]
Fails with:

```
  1) ObjectHash calculates hashes from Ruby Floats calculates the hash of common floats
     Failure/Error: raise unless s.length < 1000
     RuntimeError:
     # ./lib/objecthash.rb:122:in `float_normalize'
     # ./lib/objecthash.rb:132:in `obj_hash_float'
     # ./lib/objecthash.rb:35:in `digest'
     # ./lib/objecthash.rb:46:in `hexdigest'
     # ./lib/objecthash.rb:21:in `hexdigest'
     # ./spec/objecthash_spec.rb:218:in `block (4 levels) in <top (required)>'
```

**Comment by grempe** [comment]
I have added a pull request with enhancements to the specs in PR #6 

Hopefully @benlaurie will be able to help diagnose what is wrong in the normalize float method when compared to his version.

**Comment by grempe** [comment]
Boom. Fixed it in my PR branch. Ready for a new release now with ALL specs in the green. All spec hashes are from the output of @benlaurie objecthash (Python) implementation that I ran by hand and brought over into the Ruby specs.

**Comment by grempe** [comment]
👍 💯
